# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sarv Shakti Singh
email: singhsarvshakti127@gmail.com
description: The one who knows nothing
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hackboxlive.github.io" # the base hostname & protocol for your site
twitter_username: shakti_sarv
github_username:  hackboxlive
linkedin_username: sarv-shakti-singh
facebook_username: sarvshakt
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
